### ISSUE TITLE
HTML page language is valid is "heavy" rule (bf051a)

### ISSUE THREAD

**Issue by mraccess77** [act-rules/act-rules.github.io#1041]
The HTML page language check requires checking about 8 or 9 thousand different sub language codes.   At minimum this requires adding about 9k alone for just this check. For many checkers that isn't an issue -- but for dynamic checkers that run live adding 9k is pretty heavy.  I understand that not all rules are meant to work in all situations/context.   This issue is just to document/discuss the issue and not to hold up the test.

**Comment by WilcoFiers** [comment]
@mraccess77 Makes total sense. My suggestion would be to limit the tool to two-letter subtags. There aren't that many of those. Most of the web uses those, so that shouldn't be a big deal.

Depending on how you report the three-letter subtags, the implementation state is different:

- **failed**, that's inconsistent with the rule. I don't imagine that's what you're doing, so you should be fine.
- **passed** or **inapplicable**, this is considered a partial implementation.
- **cantTell** (or warning, notice, whatever), this is considered a semi-automated, complete implementation

There are other ways you can scope down the rule too. Scoping down rules in an implementation is fine.

**Comment by mraccess77** [comment]
Hi @WilcoFiers -- yes -- for the additional 3 letter subtag codes the implementation I'm thinking of would not fail the incorrect sub tags . Thanks for expounding on the 2 additional options in terms of partial implementation and cantTell (copmplete implementation) with cantTell being an easy to implement option.
