### ISSUE TITLE
Change the time for our second call?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1048]
A while back we scheduled a second call, EU morning / AU evening, so that folks from Asia / Australia might be able to join. Unfortunately the morning calls have not been attended by anyone from that region, and it has stopped US folks from attending. So I'm wondering if we shouldn't reschedule the 2nd monthly call to also be in a US friendly time.

**Comment by Jym77** [comment]
For the sake of "giving everybody a chance to talk", I suggest this item is actually discussed in a EU morning call… So that anybody who can only make it to one of this can actually show up and talk.
(even if this seems unlikely to happen given that there seems to be nobody in that case, it seems a bit unfair to decide to "block" people without giving them a chance to protest…)

**Comment by kasperisager** [comment]
I'm personally unable to attend meetings after 16 CET, but if I'm the only one in that situation then it doesn't really matter.
