### ISSUE TITLE
image-button acc-name does not consider default values [59796f]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1057]
In failed example 1 and 3, the default value for image buttons would give the element an accessible name, thus allowing these elements to pass:
https://act-rules.github.io/rules/59796f#failed

There are two scenarios in which failed example 1 and 3 would still fail WCAG:

1. default value for input[type=image] is not accessibility support. This has been tested by @cblouch and turns out only to be the case with Edge. https://github.com/act-rules/act-rules.github.io/pull/1033#discussion_r351489972
2. The default value does not describe the image

Unless the button was an image with the text "submit" or "submit query" on it, the default value still fails. I think we can fix this in one of two ways:

1. Don't allow default values in the expectation, and add an assumption that the default value does not describe the image.
2. Change the examples, and add an accessibility support note

I'm inclined to go with option 2, happy to discuss.

**Comment by cblouch** [comment]
As an additional data point, putting the markup:

`<input type="image" src="foo.gif" />`

On a page in Safari for iOS 12 reads as "submit button" with VoiceOver. So iOS also exercises the option of having the user agent supply an accessible name.

That said, I do question the general validity of the user agent supplying an accessible name when it has no idea what the meaning of the image is or the purpose of the button. This is probably beyond the scope of this ACT-R issue so I have filled an issue for this on the HTML Accessibility API Mappings document.
https://github.com/w3c/html-aam/issues/270#issuecomment-562176337

**Comment by cblouch** [comment]
More germane to this issue is that all three fail cases lack an accessible name from the approved attributes: aria-labelledmy, aria-label, alt and title. So all will hit step 4:

https://www.w3.org/TR/html-aam-1.0/#input-type-image

and get an accessible name from the user agent. As mentioned, while step four says "may" it seems that most UAs supply the accessible name. The net result is that if we follow the spec, not only do the three fail cases in the ACT-R test all pass, but in practice they will never fail to have an accessible name and step 5 (no accessible name) will never happen.

This seems to sweep and authoring error under the rug. I believe that in this case the UA supplied string has no way of knowing what the image is nor the purpose of the input, so it should still be flagged by the test. This means test implementation will need to take into account that for this particular type of element that it has an accessible name AND that it wasn't supplied by the user agent to pass.

**Comment by jkodu** [comment]
PR has been merged. Closing issue.
