### ISSUE TITLE
image filename, consider srcset / picture + source as well [9eb3f6]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1244]
The rule [Image filename is accessible name for image](https://act-rules.github.io/rules/9eb3f6) is limited to the `src` attribute. It could be useful to extend this rule to use srcset attributes, and to consider the `source` element if used in a `picture`.

**Comment by Jym77** [comment]
I think it would be much easier to have separate rules for these cases.

Otherwise, we're going to have a nightmarish Applicability with chains of logical connectors, something like:

the rule apply to elements with `img` role, or `input` with type "image", or `picture` when
* it is in the accessibility tree
* the accessible name is equal to the filename specified in the `src` attribute, or one of the filename specified in the `srcset` attribute on the element or one of its `source` descendant, or on the `src` attribute of the `img` descendant of a `picture` element.
