### ISSUE TITLE
Should we have warning category?

### ISSUE THREAD

**Issue by DavidMacDonald** [act-rules/act-rules.github.io#1247]
https://act-rules.github.io/rules/b20e66
Passed example 10
Links with identical accessible names have equivalent purpose - Passed Example 10

https://www.davidmacd.com/auto-test-files/act-mar17/testcases/b20e66/c983d84d427d521586e5cb1876646beabc41800e.html

2 links side by side same destination should get a best practice warning.

**Comment by WilcoFiers** [comment]
My personal opinion: 

The ACT rules format does not allow for a "warning", neither does WCAG. Something either satisfies an SC or it doesn't. Tool / methodology developers are free to mark things as warnings or for review as they like, but it isn't part of the standardisation effort, because there is no standard to back it up.

We can discuss it during an upcoming call. Would you be interested in joining us for that David?

**Comment by Jym77** [comment]
I agree that we don't really have a way to add a "warning" one way or another.

Question might be whether this example (and others on the same rule) should be updated with some text between the links to make them not adjacent (i.e., have examples follow best practices as they will be considered "examples of good code" by some).
Problem with that is that the examples would then grow with something completely unrelated to what they showcase (essentially, enough Lorem Ipsum to make these identical links not too close to each other).

This is probably related to #1165.

**Comment by WilcoFiers** [comment]
There has not been any interest in this in a while. I'm going to close the issue, and assume this is not something we're going to take on. If anyone is interested in actively working on this, feel free to open a new issue.
