### ISSUE TITLE
Joining W3C Community Slack?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1252]
Instead of having our own, should we move over to the W3C Community Slack? This was recently set up. I think this might help us connect with the W3C community, and it has the benefit of being open invite. We don't need to administrate it.

Here's the link to sign up for it: https://join.slack.com/t/w3ccommunity/shared_invite/zt-cr70arnm-znGpbS~9_7KdQ9tK9XIzMA

**Comment by Jym77** [comment]
We did decide to join the W3C slack: https://www.w3.org/2020/04/09-act-r-minutes.html#item03 and the change has been made.

Should we close this issue?

**Comment by Jym77** [comment]
@WilcoFiers is it possible to add a link to our slack channel from the [CG web page](https://www.w3.org/community/act-r/) "Tools for this group" (rather than a link to some irc…)

Should we update https://act-rules.github.io/pages/contribute/#join-the-community-group to mention the Slack channel?

Other than these, I think the issue can be closed.
