### ISSUE TITLE
Autocomplete, note that it also passes with autocomplete=off on the form (73f2c2)

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1400]
As in title

```html
<form autocomplete="off">
  <input autocomplete="given-name" />
</form>
```

**Comment by ajanec01** [comment]
I've checked in Firefox using below query and the attribute value was returned.

```
document.querySelector('input').getAttribute('autocomplete');
```

Should I create a PR for it?

**Comment by patrickhlauke** [comment]
you may want/need to test the autocomplete property of the element, not the attribute defined in the markup?

**Comment by ajanec01** [comment]
Hi Patrick

Thanks for that! I kind of guessed that wasn't right. I've checked that now by creating a form variable and accessed the input property like this `form[0].autocomplete`.

Chrome returns the defined value irrespectively of the `autocomplete="off"` on the `<form>`. Firefox returns an empty string irrespectively of the value on `<form>`. 

I then realised [ you had all that covered elsewhere on github](https://github.com/w3c/wcag/issues/1197#issuecomment-659249937) :)

Now, I'm not sure it's a good idea to include it in one of the examples as it doesn't seem to be supported well in Firefox.

**Comment by ajanec01** [comment]
There is something else I'm wondering about now. I've changed the above example to include the `type` attribute in the `password` state. Technically, it should fail as per [failed example 5.](https://act-rules.github.io/rules/73f2c2#failed-example-5) but I could still query it using `form[0].autocomplete`. 

The example is failing the [autocomplete attribute has valid value](https://act-rules.github.io/rules/73f2c2) rule because of expectation 3 (appropriate control group) but it doesn't fail 1.3.5.

Please check me on that.

**Comment by WilcoFiers** [comment]
Can you include the code snippet @ajanec01?

**Comment by ajanec01** [comment]
```
<form autocomplete="off">
  <input type="password" autocomplete="given-name">
</form>
```
```
document.querySelector('input').autocomplete
```

The output is `"given-name"` (in Chrome)
