### ISSUE TITLE
Define "text background color"

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#141]
Backgrounds for texts can consist of e.g. solid background colors, images, gradients and patterns. The presentation of the background can further be altered using e.g. transparency, semi-transparent overlays, blend-modes and text-shadows.

When calculating the text background color for use in color contrast calculations, the background area of a text is considered to cover the smallest possible box that fits a [word](#word) + 25% of the font size of the text in padding around the box. 
Note that the background area might change depending on e.g. breakpoints and zoom.

The text background color is a spectrum of color values, ranging from an estimated average dark color to an estimated average light color found in the background area of the text.

To find an estimated darkest color in the background area, sample 5 of the darkest colors in the background area as defined by [relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef), and choose the color with the lowest value (the value closest to 0, where 0 represents the darkest black).

To find an estimated lightest color in the background area, sample 5 of the lightest colors in the background area as defined by [relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef), and choose the color with the highest value (the value closest to 1, where 1 represents the lightest white).

If all the colors sampled are the same, a single value can be used for the relative luminance of the background.

**Comment by kasperisager** [comment]
My plan is to create a separate algorithm for determining _if_ a solid background color can be reliably determined.

**Comment by WilcoFiers** [comment]
I'm not sure what the point is of having a rule that only tests elements with a solid background color. It seems to me that when you can do that, you can also determine all the color something is on top of, which lets you determine if there are colors that may not pass.

**Comment by kasperisager** [comment]
In the majority of cases, text will be rendered on solid backgrounds. The remaining cases more often than not require manual review as the exact pixels that text is rendered on top of will depend on a number of different things. It makes sense to me to cover these cases separately; the simple and reliable ones, and the more complex ones that likely require review.

**Comment by gianwild** [comment]
However if there is a patterned background, you don’t know the background color as it changes depending on text size and window size. What may pass on desktop will fail on mobile or at 250%. That is why proper color contrast testing is so hard to do, unless there is a solid background color.

Cheers,
Gian

**Comment by WilcoFiers** [comment]
I disagree that plain background is the "simple" case. The way you're proposing to scope this rule seems pretty arbitrary to me. No expert evaluator would ever consider those two separate tests. I'm happy to let you work on a precise definition that will only pull up a single background color. We have one in Axe-core and it is horrendously complicated. In hindsight the better solution would have been to collect as many colours as we can find and compute the contrast on all of them. If they all pass, we're good, if they all fail, it's a violation - if some pass and others don't, human please have a look.

A rule like that is far easier to write, far easier to use in manual evaluations, and for tool developers it really shouldn't be all that different to return "cannotTell" instead of "inapplicable".

**Comment by WilcoFiers** [comment]
Also please remember that "plan language" requirement that both expectations and applicability have to meet.

**Comment by annethyme** [comment]
Kasper, Wilco, Jey and Anne have agreed that we need to give this algorithm another shot, keeping it less implementation specific, closer to plain language and using test cases to decide whether different implementations meet the expectations. 

### Kasper's original proposal, saved for later reference: 

> This is my attempt at defining a method for determining background colors of elements in a way that allows us to independently deal with special cases such as non-statically positioned elements and background images. For example, we might want to create rules that test for offline access, in which case images might not even be available.

The solid background color of an element is the background color on which text nodes that are direct children of the element will, in theory, be rendered. It is solid in the sense that all characters of direct child text nodes will, in theory, be rendered on the same background color. In practice, things such as background images and non-statically positioned parent elements might cause the actual background color of the element to be non-solid, depending on network conditions in the case of images and screen dimensions in the case of non-statically positioned parent elements.

The solid background color of an element is determined as follows:

1. Let `background color` be the [computed](https://www.w3.org/TR/css-cascade/#computed) [`background-color`](https://www.w3.org/TR/css-backgrounds/#propdef-background-color) of the element.

2. Multiply the [alpha value](https://www.w3.org/TR/css-color/#typedef-alpha-value) of `background color` by the computed [`opacity`](https://www.w3.org/TR/css-color/#propdef-opacity) of the element.

4. If `background color` has an alpha value equal to 1, let `background color` be the result of this algorithm.

5. Otherwise, let `parent background color` be the result of determining the solid background color of the parent element of the current element starting with step 1. If no parent element exists, let `parent background color` be [white](https://www.w3.org/TR/css-color/#valdef-color-white).

6. Let the result of this algorithm be the result of applying [simple alpha compositing](https://www.w3.org/TR/compositing/#simplealphacompositing) on `background color` with `parent background color` as the [backdrop](https://www.w3.org/TR/compositing/#backdrop).

**Comment by jkodu** [comment]
useful for issue #405

**Comment by WilcoFiers** [comment]
Talked to @kasperisager about some way to progress on this rule. Some notes:

We need definition of:

- text
- text colors
- background colors
- Bold text (font weight is a lie)

We should try to come up with the following two values:
- Highest possible contrast
- lowest possible contrast

Based on that, there are three possible outcomes:

- Highest possible isn't enough = fail
- Lowest possible contrast is enough = pass
- TODO: figure out how to describe this for user review

**Comment by WilcoFiers** [comment]
## Expectation 1

The lowest possible contrast is more than 4.5:1 (or 3:1)

## Expectation 2

What we know:
- The size of the area that has insufficient contrast matters to whether or not this fails
- The how far the low contrast area is removed from the minimal contrast does not matter
- ... what about the length of the text. Reading a single word that's partially obscured is less burdensome than reading a whole paragraph where every word id partially obscured.

**Comment by annethyme** [comment]
@kasperisager and @WilcoFiers, can we close this one as being replaced by https://github.com/act-rules/act-rules.github.io/issues/571 ?

**Comment by WilcoFiers** [comment]
Superseded by #571.
