### ISSUE TITLE
ARIA required owned, do we need the no implicit requirement? bc4a75

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1413]
Got some more feedback on the following line, this time from the ACT TF:

> the element has an implicit semantic role that is identical to its explicit semantic role; or

Now that I've seen what the content model rules look like, this might not be necessary anymore. Need to think through the different cases.

**Comment by Jym77** [comment]
I must say I was never a big proponent of the "no implicit" exception in "required context role" and "required owned element" rules…

As far as I remember, this exception is due to the fact that with implicit role the lack of required context/owned would **also** be a failure of 4.1.1 Parsing. I think the situation is very similar to the "button has accessible name" rule carefully avoiding image buttons because they would **also** fail 1.1.1.

We kinda discussed the situation (for button/image buttons) and concluded (iirc) to remove the "image button" exception (even though this was never really finished @EmmaJP ) See #1049, #1184 and https://www.w3.org/2020/02/13-act-r-minutes.html#x03

I think we are in a similar situation here. My position would be to remove the "no implicit" exception which is very weird and forces the examples to also be very weird (notably breaking the [First rule of ARIA](https://www.w3.org/TR/using-aria/#rule1)).
I am also not sure how frequent it is "in the wild" to have an explicit role different from the implicit, **and** with required context/owned roles…

Note that in Alfa we decided to ditch the "no implicit" exception from both context/owned rules as it streamlines things a lot.

**Comment by ajanec01** [comment]
Hey @WilcoFiers 

Would it be worth adding it as an agenda item? I'm happy to create a PR to clear issues related to the [feedback on ARIA required owned elements](https://github.com/w3c/wcag-act/issues/468).
