### ISSUE TITLE
Remove accessibility support sections from the glossary

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1416]
Similar to how we're taking the examples out of the definitions, having accessibility support headings within definitions breaks up the flow of a document quite substantially. Instead of having accessibility support notes inside the definition itself, I think this information belongs in the accessibility support section of each rule.

**Comment by Jym77** [comment]
I agree that Accessibility Support, and Assumptions, should only exist at the rule level, not at the definition level.

However, when a definition is having poor Accessibility Support, or is making an assumption, then this trickle down to all rules using it.

From a producer point of view, I see Accessibility Support, and Assumptions, in definitions as a reminder that if my rule uses this definition, then it must include these concerns. For this reason, I feel they are useful inside the source file of the definition because it is easy to forget about them when re-using an old definition.

From a consumer point of view, I agree that it doesn't make the rule very readable to have Accessibility Support and Assumptions in the definition, nor to have them duplicated in both the rule and definition.

In an ideal word, the building process could extract the Accessibility Support, and Assumptions, from definitions and automatically include them in rules. This is not really possible as it is guaranteed to end up with weird sentences, duplicate concerns, …

**Comment by WilcoFiers** [comment]
Discussed on the CG call today. Decided to filter out sectioned content from definitions, so that the accessibility support / assumptions can be put into the glossary page, but would be left out of the rules page. This'll require an update to the website.

**Comment by Jym77** [comment]
> Discussed on the CG call today. Decided to filter out sectioned content from definitions, so that the accessibility support / assumptions can be put into the glossary page, but would be left out of the rules page. This'll require an update to the website.

This could be used for other sections in definition, typically Examples that have been moved to separate page recently. As much as it makes sense to hide them from the Rule pages, I think it would be beneficial to keep them in the Glossary page where the definitions are well separated. See also #1472.

Also, with the definition in the Rule pages becoming a stripped down version of the full Definition, I feel there should be a link from the "definition in the rule" to the "full definition in Glossary page". That is, https://act-rules.github.io/rules/97a4e1#accessible-name should have a link to https://act-rules.github.io/glossary/#accessible-name so that reader can get the full details if they want.

**Comment by WilcoFiers** [comment]
When moving content to the WAI website, I'm taking out all content under heading in the definitions. This should now be addressed. We can freely add heading to definitions, and reuse their content in the rules.
