### ISSUE TITLE
Rejected/clarification needed - "audio element content is media alternative for text" (afb423)

### ISSUE THREAD

**Issue by susanatx** [act-rules/act-rules.github.io#1580]
It isn't clear how this rule is different from "audio element content has text alternative". Does this check if the text alternative accurately reflects the audio (which seems to be what failure 1 covers in e7aa44)?

**Comment by tbostic32** [comment]
Adding on my concerns with accepting this rule:

- I would like to discuss expectation 2 and 3 more. Since these are not programmatic labels I had concerns if this could be ambiguous. 
- I think expectation 2 and 3 could be joined as well.

**Comment by tbostic32** [comment]
Since this was in the first batch, the rule honestly could have been accepted, we were just a little bit more strict to start. In the merge above I posted a change to combine expectation 2 and 3 which does fit the same pattern as [video element content is media alternative for text](https://act-rules.github.io/rules/ab4d13).

@susanatx As for your question, `audio element content has text alternative` is the composite rule that encapsulates `audio element is media alternative`. What that means is the `media alternative` rule is one way that the composite rule can be satisfied, but it can also be satisfied by its other atomic rule [audio element content has transcript](https://act-rules.github.io/rules/2eb176). In other words, either of these design patterns is acceptable an the composite rule is checking that one of them is used. Hopefully that clears things up!
