### ISSUE TITLE
[Quick Review] Document has a landmark with non-repeated content

### ISSUE THREAD

**Issue by tbostic32** [act-rules/act-rules.github.io#1585]
Rule Link: https://act-rules.github.io/rules/b40fd1

@daniel-montalvo Since you are the other person reviewing this rule, I would appreciate your feedback/discussion on any of the items below.

- Repeated content assumes some repetition over some set of web pages. The applicability is currently only for any HTML web page, which i think leaves what is and isn't repeated content up for discussion. I am wondering if there is a missing assumption or test case description that would help define the repeated content for this case. 
- The background sentences "... this rule passes by enclosing primary content of the page in a main landmark" and "In most examples the nav element is a block of repeated content" seem out of place. 
- I find the expectation somewhat difficult to understand, which may be due to the test case descriptions not explicitly referencing which part of the expectation allows them to pass/fail, primarily for bullet point 2 of the expectation it took a while to wrap my head around it.

I considered the rule rejected for the moment, but these may not be blockers.

**Comment by daniel-montalvo** [comment]
> Rule Link: https://act-rules.github.io/rules/b40fd1
> 
> @daniel-montalvo Since you are the other person reviewing this rule, I would appreciate your feedback/discussion on any of the items below.
> 
> * Repeated content assumes some repetition over some set of web pages. The applicability is currently only for any HTML web page, which i think leaves what is and isn't repeated content up for discussion. I am wondering if there is a missing assumption or test case description that would help define the repeated content for this case.

I think the applicability should remain as-is. I am afraid including explicit reference to [block of repeated content](https://act-rules.github.io/rules/b40fd1#block-of-repeated-content) in the applicability is not allowed in the ACT Rules format, as it is not an objective definition. Would including an assumption that each test target is within a set of web pages work?

> * The background sentences "... this rule passes by enclosing primary content of the page in a main landmark" and "In most examples the nav element is a block of repeated content" seem out of place.

My understanding is that these are good hints for people to better understand some of the most common scenarios. Not a big issue for me, though.

> * I find the expectation somewhat difficult to understand, which may be due to the test case descriptions not explicitly referencing which part of the expectation allows them to pass/fail, primarily for bullet point 2 of the expectation it took a while to wrap my head around it.

There is some editorial pass needed for the test descriptions to adapt them to the current style. In addition, we could tweak them to better map to the expectations. For example, in the first passed test case description, my understanding is that you would expect something like

> This main element has a node with non-repeated content after repeated content as its first perceivable content which is included in the accessibility tree.

This would be weird to me, especially because we say in the expectations that all of the conditions need to be true for the test case to pass. Would we be repeating these in each of the descriptions?

> I considered the rule rejected for the moment, but these may not be blockers.

Happy to discuss these on the meeting. I do acknowledge that this rule may need some more clarification, but I am hesitant to consider these as blockers based on last week's discussions for other similar issues.

**Comment by Jym77** [comment]
> Rule Link: https://act-rules.github.io/rules/b40fd1

> * Repeated content assumes some repetition over some set of web pages. The applicability is currently only for any HTML web page, which i think leaves what is and isn't repeated content up for discussion. I am wondering if there is a missing assumption or test case description that would help define the repeated content for this case.

See the discussion at #1588 which is also an atomic rule for the same composite.
(on a side note, I think it might have been an error to review the atomic rules individually and independently from their composite rule, especially with different person reviewing each, in that case, there is a real need to keep the big picture in mind to understand the rules, and using or evaluating them in isolation is bound to produce weird results)

> * The background sentences "... this rule passes by enclosing primary content of the page in a main landmark" and "In most examples the nav element is a block of repeated content" seem out of place.

I considered that each example would need to mention what is its repeated content. Especially since this is a subjective definition, so it is needed to make it crystal clear or people might disagree on the examples for the wrong reasons. Then, I feel that adding this note to every single example description would feel very redundant, so it ended up in the Background which felt like an OK place for a generic explanation of examples… (I also put it after the bibliography to try and show it is at a different level than the other background notes). I guess this doesn't work as it intended 😅 

> * I find the expectation somewhat difficult to understand, which may be due to the test case descriptions not explicitly referencing which part of the expectation allows them to pass/fail, primarily for bullet point 2 of the expectation it took a while to wrap my head around it.

Yes, the expectation is a bit complex, and it felt like repeating it at every example description would be very redundant and not necessarily helping.
A correct description for the first Passed Example might be:
> In this document, the main element has a semantic role of main, has the `p` element as its first perceivable content descendant which is non-repeated and after the repeated `nav` element, and is included in the accessibility tree.

but I'm not sure this really make it easier to read (especially when repeated on each example…)
This is probably a rule where the Failed Examples are more helpful in understanding the Expectation (since each fails for one reason, and the reason is stated). This might also benefits from having [Listed conditions](https://act-rules.github.io/pages/design/rule-design/#listed-conditions) with names to refer to them.
