### ISSUE TITLE
ARIA Valid Value (6a7281) Pass Example 4 idref missing

### ISSUE THREAD

**Issue by tombrunet** [act-rules/act-rules.github.io#1617]
Rule: https://act-rules.github.io/rules/6a7281
Passed example 4: https://act-rules.github.io/testcases/6a7281/23f69af205f3c0032d60d64288fe96c59e2b0fa2.html
```
<div role="textbox" aria-errormessage="my-error" aria-label="A textbox"></div>
```
Simply says 
> aria-errormessage property with valid ID reference value

But, `#my-error` doesn't exist in the testcase, so the ID reference isn't valid...

**Comment by tombrunet** [comment]
I saw a note in another issue about 'maybe' ignoring idrefs that aren't required. If that's the situation, would be nice to update the passing explanation. Otherwise, seems like the my-error reference needs to be added. I'm not sure which of the two is intended (feels like a valid id ref should be added to the testcase). Allowing for an invalid id-ref simply because that field isn't required feels like it's asking for trouble - devs won't be alerted to all sorts of bad refs.

**Comment by tombrunet** [comment]
I can, but I'm not familiar with the testcase update process, and I don't see them in the repo. Do testcase ids change on update?

**Comment by tombrunet** [comment]
A possible update would be:
```
<div role="textbox" aria-errormessage="my-error" aria-label="A textbox"></div>
```

**Comment by Jym77** [comment]
> I can, but I'm not familiar with the testcase update process, and I don't see them in the repo.

That's why I'm suggesting you do it so you can learn the process 😉 

The test cases are stored as part of the rules. So you can edit the rule file itself (https://github.com/act-rules/act-rules.github.io/blob/develop/_rules/aria-state-or-property-valid-value-6a7281.md and click on the pen in the top right area).
When you save your changes, you'll be offered to create a new branch (probably a "fork" branch, not 100% sure) and a Pull Request.
