### ISSUE TITLE
Test case in Zoomed text node is not clipped with CSS overflow

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules.github.io#1638]
[Rule Id: 59br37](https://act-rules.github.io/rules/59br37)

Failed Ex 3 didn't fail using Edge until 300%. Failed in Chome at 200% though.

**Comment by tbostic32** [comment]
Didn't have time to dig into this, but I did test it as well and had the same experience. I am wondering if there is some accessibility support addition since edge seems to be doing something a little different than chrome and firefox. I'm unsure if this should be a blocker for the rule though.

**Comment by Jym77** [comment]
The test case depends on media query and thus on how the browser resolves it…

Clipping occurs when the `@media screen and (max-width: 640px)` trigger at a width below `640px`. I can trigger it both in Chrome and Edge by shrinking the window (and no zoom).
I can also trigger it by having a smalll-but-not-too-small window (around 700 or 800 px) and zooming in. Both Chrome and Edge clip in my case.

**Comment by WilcoFiers** [comment]
Alright, so I've done a bunch of testing for this. The problem seems to occur specifically with Edge device simulator. I can't quite figure out why, but it doesn't pick up the media query. if you actually adjust the window to be 640px wide, Edge behaves the same way every other browser does, and content correctly gets clipped

I think this is a bug in Edge DevTools, and so I don't think it will impact any users. I think this issue can be closed.
