### ISSUE TITLE
Should "Link has non-empty name" apply to inheriting links? [c487ae]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1670]
I noticed this rule applies to semantic links. Seems to me this should also apply to inheriting semantic links.

On the other hand though, should we expect anyone testing HTML to support DPUB? Should that be in a separate rule?

**Comment by Jym77** [comment]
Maybe we can have a failing example with `<span role="doc-biblioref link">` so that:
* tools that don't support DPUB fail that as being a semantic link without name;
* tools that support DPUB and correctly check for non-empty name of inheriting semantic links fail that;
* tools that support DPUB but only check for non-empty name of semantic links (non inheriting ones) incorrectly pass that.

That way, tools that don't fail the example are tools that do not correctly implement the rule within their ARIA capacities; and we don't "punish" tools that chose to ignore DPUB.
