### ISSUE TITLE
"Orientation of the page is not restricted using CSS transform property" [b33eff]: Failed example 3 doesn't show on screen

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1782]
When looking at [Failed example 3](https://act-rules.github.io/testcases/b33eff/a3781bdaef2c50a9a60b2c9ab749418be195017b.html) of rule [Orientation of the page is not restricted using CSS transform property](b33eff), in landscape mode on a wide screen, the page looks empty.
This is likely due to the wide `body` element being rotated on its rightmost corners and thus the small text on the left side got pushed off-screen at the top.

We should likely make sure there actually is something visible on both orientations.
(other examples of this rule might suffer from similar problems on either orientation, I haven't double checked all of them).

<img width="1798" alt="Screenshot of Failed Example 3, showing the rotated body element with its beginning pushed off-screen" src="https://user-images.githubusercontent.com/19969498/149913852-ecf60286-fcdb-4a00-ad48-5fc6a1b91ec0.png">

**Comment by WilcoFiers** [comment]
This also seems to happen to inapplicable example 3 and 4.

**Comment by tombrunet** [comment]
@WilcoFiers Created a PR. I did not touch inapplicable 3 because it's hidden intentionally (It's not applicable because it's display none and therefore not visible).

It was a little trickier than first thought because, while the rotation is fixed, the distance the text moves depends on the size of the box rotating (browser width/height). I think the CSS I added should limit this enough to at least let the test cases do what they're supposed to.
