### ISSUE TITLE
Should ARIA IDREFs existing be required? [6a7281]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1849]
For the [ARIA state or property has valid value](https://www.w3.org/WAI/standards-guidelines/act/rules/6a7281/proposed/) rule, the expectation says: 

> For value types ID Reference and ID Reference List for [WAI-ARIA required properties](https://www.w3.org/TR/wai-aria-1.1/#requiredState) at least one of the elements with the given ids exists in the same [document tree](https://dom.spec.whatwg.org/#document-trees) or in the same [shadow tree](https://dom.spec.whatwg.org/#shadow-trees) as the element that specifies the target attribute.

This is then tested with failed example 4. This is actually a pretty good example of why we shouldn't strictly require these elements to exist. Take for example the following component (in Vue):

```html
<p v-if="error" id="error">{{ error }}<p>
<label>
  name <input aria-errormessage="error" aria-invalid="{{ error ? true : false }}">
</label>
```

In this scenario, while there is an error, aria-errormessage works. When there is no error, the `p` element is not in the DOM, and so `aria-errormessage` does nothing. I think this is a legitimate way of building such a component, one that I've seen more than a few times. I think we should get rid of this requirement. Either that or be more selective about which attributes do, and which co not require IDREF to exist. The most important one is use of aria-labelledby, but if those reference don't work we have rules that catch problems with empty accessible names.

**Comment by Jym77** [comment]
It is only the **required** properties that need a valid element for this rule.
In your example, `aria-errormessage` is not required by `textbox` therefore the rule passes (this is essentially Passed Example 4 of the same rule).
In Failed Example 4, the problem is that a single ID property (`aria-errormessage`) has a value that contains a space and therefore is not a single IDref.

It seems this discussion more or less already happened when the rule was written:
* https://github.com/act-rules/act-rules.github.io/pull/233#discussion_r213000972 Initially it was required on all attributes and requested to be removed.
* https://github.com/act-rules/act-rules.github.io/pull/233#discussion_r221876885 Next, it was re-added for required `aria-*` attribute only.
* https://github.com/act-rules/act-rules.github.io/pull/233#discussion_r223781532 And the same discussion as this one happened.

There is also a [background note](https://www.w3.org/WAI/standards-guidelines/act/rules/6a7281/proposed/#background) detailing all this.

**Comment by Jym77** [comment]
Also, note that `aria-control` is no more required on `combobox` in ARIA 1.3: https://w3c.github.io/aria/#combobox

**Comment by Jym77** [comment]
ARIA PR that removed the requirement for `aria-controls` on `combobox`: https://github.com/w3c/aria/pull/1335

I think we should follow suit, even if it's only in ARIA 1.3, because the authoring practice say so. So, add an extra exception for it with a background note explaining the reasoning.
