### ISSUE TITLE
Update Rule: ARIA state or property has valid value

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#365]
Rule: https://auto-wcag.github.io/auto-wcag/rules/SC4-1-2-aria-state-or-property-has-valid-value.html

In the below scenario, the rule fails SC 4.1.2, but it should fail SC 1.3.1 instead, because 4.1.2 does not tackle relationships between owned and context elements.

Suggestions:
- We add 1.3.1? but there is already 2 other PR for a rule which goes into greater detail of owned and context elements - https://github.com/auto-wcag/auto-wcag/pull/255 and https://github.com/auto-wcag/auto-wcag/pull/245
- Change the rule to only look at STATES and not PROPERTY.

Thoughts welcome.

![image](https://user-images.githubusercontent.com/20978252/49580384-b4bb4980-f946-11e8-82a7-3df536483b0e.png)

**Comment by jkodu** [comment]
Todo:

Go through `aria` spec, and sort the properties into the respective S.C bucket.

**Comment by jkodu** [comment]
@WilcoFiers - see above for tabulation of SC vs states and properties.

**Comment by annethyme** [comment]
I am assigning this rule to myself since I am the owner of this rule inside the WAI-Tools project. It has a deadline of March 31.

**Comment by annethyme** [comment]
Related to https://github.com/auto-wcag/auto-wcag/issues/376

**Comment by annethyme** [comment]
Building further on Jey's analysis...

State/ Property | type | SC | Description
---|---|---

aria-activedescendant | property | []() | Identifies the currently active element when DOM focus is on a composite widget, textbox, group, or application.


aria-atomic | property | [4.1.3](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) | Indicates whether assistive technologies will present all, or only parts of, the changed region based on the change notifications defined by the aria-relevant attribute.

aria-autocomplete | property | [1.3.5](https://www.w3.org/TR/WCAG21/#identify-input-purpose) | Indicates whether inputting text could trigger display of one or more predictions of the user's intended value for an input and specifies how predictions would be presented if they are made.

aria-busy | state | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates an element is being modified and that assistive technologies MAY want to wait until the modifications are complete before exposing them to the user.

aria-checked | state | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates the current "checked" state of checkboxes, radio buttons, and other widgets. See related aria-pressed and aria-selected.

aria-colcount | property | Defines the total number of columns in a table, grid, or treegrid. See related aria-colindex.

aria-colindex | property | Defines an element's column index or position with respect to the total number of columns within a table, grid, or treegrid. See related aria-colcount and aria-colspan.

aria-colspan | property | Defines the number of columns spanned by a cell or gridcell within a table, grid, or treegrid. See related aria-colindex and aria-rowspan.

aria-controls | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Identifies the element (or elements) whose contents or presence are controlled by the current element. See related aria-owns.

aria-current | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates the element that represents the current item within a container or set of related elements.

aria-describedby | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Identifies the element (or elements) that describes the object. See related aria-labelledby.
aria-details | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Identifies the element that provides a detailed, extended description for the object. See related aria-describedby.

aria-details | property | 

aria-disabled | state | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. See related aria-hidden and aria-readonly.

aria-dropeffect | property | ???? | [Deprecated in ARIA 1.1] Indicates what functions can be performed when a dragged object is released on the drop target.

aria-errormessage | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Identifies the element that provides an error message for the object. See related aria-invalid and aria-describedby.

aria-expanded | state | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed.

aria-flowto | property | [1.3.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html) | Identifies the next element (or elements) in an alternate reading order of content which, at the user's discretion, allows assistive technology to override the general default of reading in document source order.

aria-grabbed | state | ???? | [Deprecated in ARIA 1.1] Indicates an element's "grabbed" state in a drag-and-drop operation.

aria-haspopup | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by an element.

aria-hidden | state | [1.1.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html) | Indicates whether the element is exposed to an accessibility API. See related aria-disabled.

aria-invalid | state | [3.3.1](https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/minimize-error-identified.html) | Indicates the entered value does not conform to the format expected by the application. See related aria-errormessage.

aria-keyshortcuts | property | NONE | Indicates keyboard shortcuts that an author has implemented to activate or give focus to an element.

aria-label | property | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Defines a string value that labels the current element. See related aria-labelledby.

aria-labelledby | property | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Identifies the element (or elements) that labels the current element. See related aria-describedby.

aria-level | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the hierarchical level of an element within a structure.

aria-live | property | [4.1.3](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) | Indicates that an element will be updated, and describes the types of updates the user agents, assistive technologies, and user can expect from the live region.

aria-modal | property | NONE | Indicates whether an element is modal when displayed.

aria-multiline | property | NONE | Indicates whether a text box accepts multiple lines of input or only a single line.

aria-multiselectable | property | NONE | Indicates that the user may select more than one item from the current selectable descendants.

aria-orientation | property | NONE | Indicates whether the element's orientation is horizontal, vertical, or unknown/ambiguous.

aria-owns | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Identifies an element (or elements) in order to define a visual, functional, or contextual parent/child relationship between DOM elements where the DOM hierarchy cannot be used to represent the relationship. See related aria-controls.

aria-placeholder | property | NONE | Defines a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value. A hint could be a sample value or a brief description of the expected format.

aria-posinset | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines an element's number or position in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM. See related aria-setsize.

aria-pressed | state | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Indicates the current "pressed" state of toggle buttons. See related aria-checked and aria-selected.

aria-readonly | property |  NONE | Indicates that the element is not editable, but is otherwise operable. See related aria-disabled.

aria-relevant | property | [4.1.3](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) | Indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified. See related aria-atomic.

aria-required | property | [3.3.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html) | Indicates that user input is required on the element before a form may be submitted.

aria-roledescription | property | NONE | Defines a human-readable, author-localized description for the role of an element.

aria-rowcount | property |  [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the total number of rows in a table, grid, or treegrid. See related aria-rowindex.

aria-rowindex | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines an element's row index or position with respect to the total number of rows within a table, grid, or treegrid. See related aria-rowcount and aria-rowspan.

aria-rowspan | property |  [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the number of rows spanned by a cell or gridcell within a table, grid, or treegrid. See related aria-rowindex and aria-colspan.

aria-selected | state | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Indicates the current "selected" state of various widgets. See related aria-checked and aria-pressed.

aria-setsize | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the number of items in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM. See related aria-posinset.

aria-sort | property | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Indicates if items in a table or grid are sorted in ascending or descending order.

aria-valuemax | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the maximum allowed value for a range widget.

aria-valuemin | property | [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) | Defines the minimum allowed value for a range widget.

aria-valuenow | property | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Defines the current value for a range widget. See related aria-valuetext.

aria-valuetext | property | [4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html) | Defines the human readable text alternative of aria-valuenow for a range widget.

**Comment by WilcoFiers** [comment]
@annethyme Here are 3 proposals that I would be okay with, please let me know which one's you think could be adopted in Alpha.

1. Add a mapping to ARIA 1.1, leaving 4.1.2 in there, and adding an assumption about all elements with `aria-*` or `role` being user interface components.
2. Duplicate the rule specifically for mapping to ARIA, so we have one rule that maps to ARIA without assumptions, and a second that maps to WCAG 4.1.2 with assumptions
3. Split the rule up over two or more rules (TBD), with the combined scope similar to the scope of the existing rule, and those rules mapping to at least one WCAG success criterion.

**Comment by annethyme** [comment]
No matter what course this take, we suggest editing the Applicability to handle other comments that have come in. I gave it a shot in https://github.com/auto-wcag/auto-wcag/pull/464.

**Comment by annethyme** [comment]
Three different draft rules that tried to take on the challenge of creating a rule for (some of) this where we could all agree on the accessibility requirement mapping: #441, #454, #464

**Comment by jkodu** [comment]
Tackled in merged PR's
- https://github.com/act-rules/act-rules.github.io/pull/607
- https://github.com/act-rules/act-rules.github.io/pull/639
