### ISSUE TITLE
Github permissions and group participation

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#371]
Currently, over 32 people have write access to the Auto-WCAG repository. The way things have worked up until now is that anyone interested in contributing to Auto-WCAG has been given 'write' access to the repository. This means that everyone is able to approve pull requests, and everyone is able to edit and delete issues and comments. The only restriction that is in place, which was only introduced recently is that only administrators are allowed to merge changed to the master branch.

The current situation has a number of problems with it:

1. There is no requirement for approving a rule, any member can review and approve a rule. Well intentioned newcomers can approve a change with obvious problems in them.

2. It leaves the repository open to vandalism. The more people are given the opportunity to do harm, the greater the risk to the project. 

----

Proposal:

1. By default, Auto-WCAG (ACT Rule CG) members will not be made collaborators on Github. Everyone will still be able to review pull requests. But pull requests can not be approved, and new pull requests can only be created through a fork.

2. Anyone writing rules, or who can demonstrate familiarity with the ACT Rules Format will be invited to be given "read" access to the repository upon joining the community group. This enables them to approve pull requests.

3. Frequent contributors can be given write access upon request, and provided they have authored or reviewed up to three rules in the past year.

4. Admin access is restricted to the community group chair(s), and the W3C facilitator. Someone can be given temporary admin access for specific tasks. This access must be revoked after the task is completed.

**Comment by jkodu** [comment]
+1 for the proposal 👍

**Comment by nitedog** [comment]
I'm OK with constraining write/admin access.

However, I'm concerned about over-constraining review/approval. I, for one, do not plan to author any rules. This means I will not be able to approve rules. Maybe that is good but maybe you are overly reducing the potential group of reviewers, rather than involving more people in the process. We already have too few people involved, and putting such restrictions is likely to further reduce this group. There can be other ways to improve quality assurance, for example by making it easier to review and approve rules to help expand the group of reviewers, provide clearer instructions for review and approval, and by requiring more reviews if necessary.

**Comment by EmmaJP** [comment]
Sounds very similar to the set-up we now have for the bbc-a11y tool. 

Anyone can fork the repository and make changes in a committed branch on that fork and submit a pull request. Only contributors with the right permissions on the main repo can approve and merge pull requests. And only some of those contributors currently have the additional permissions to push out a new release version.

**Comment by jkodu** [comment]
This has been discussed in various ACT-R calls & the current set-up for permissions seems to work, hence closing the issue.
