### ISSUE TITLE
Migrating the Auto-WCAG repository

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#471]
With the new ACT-R Community Group set up now, we need to migrate our Github repository as well. There are two things we can do here:

1. Rename the organisation and repository
2. Fork the repository to w3c/wcag-act-rules

Advantage of the first one is we can do that without losing any of the repository's history. We'd keep all open and closed pull requests, issues, etc. If we fork (which I think is @nitedog's prefer solution) we have to migrate everything, but we would have the repository be directly associated with the W3C, which is I think helps legitimise the work.

**Comment by nitedog** [comment]
I don't understand the technicalities of fork, move, and rename. I'm also not stuck on the particular repo w3c/wcag-act-rules -- maybe we could use that separately as the repo for rules that eventually become approved by AGWG. My suggestion is to merely have the (new?) ACT-R repo under W3C organization because of the following reasons:

1. benefit from the W3C back-up and archiving of W3C repos
2. provide an organizational ownership that is not dependent on any one particular person/group
3. provide more credibility and "ligitimization" as @WilcoFiers puts it

**Comment by WilcoFiers** [comment]
Repo has been moved. We may revisit moving this repo over to the W3C organisation, but for the time being, this issue is done.
