### ISSUE TITLE
Composite rule (c3232f) with another composite rule as input

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#625]
Rule https://act-rules.github.io/rules/c3232f "video only has an accessible alternative" is listing rule https://act-rules.github.io/rules/eac66b "Video has audio alternative" as input rule.

However, both are composite rules and the ACT-R format requires that only atomic rules can be input of composite rules.

My guess is that the input rule should rather be "Video **only** has audio alternative" (which does not exist yet).

**Comment by annethyme** [comment]
@ShadowBB and @WilcoFiers, you were the original authors for this rule. Could you maybe help provide a bit of clarity on this?
Or is the composite-composite rule on purpose? It is currently not in lign with the ACT Rules Format on this, but there has already been discussions about allowing composite-composite rules.

**Comment by ShadowBB** [comment]
This issue is indeed an issue.

According to the media plan (https://github.com/act-rules/act-rules.github.io/issues/180) this should indeed have input from a rule called "Video only has audio alternative".

In fact, in the original pull request this was the case:
https://github.com/act-rules/act-rules.github.io/pull/276/files

I am unsure how that got changed later on but we should reverse that change.

We should revert his change and link to the correct rule (that does already exist):
https://github.com/act-rules/act-rules.github.io/blob/develop/_rules/video-only-audio-alternative-d7ba54.md

**Comment by Jym77** [comment]
@jkodu Ain't this one closed by your recent PRs?

**Comment by jkodu** [comment]
Yup. true. Can close this @Jym77
