### ISSUE TITLE
Consider using accessibility tree as an input aspect

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#638]
Based on a discussion here: https://github.com/w3c/wcag-act/issues/370

I believe that because we don't have an unambiguous and objective definition of the accessibility tree, we shouldn't treat it as though it's something that's the same everywhere. If we approach the accessibility tree as a black box that can differ in different browsers, and that is something tools may or may not simulate, we clarify why the same rule, run with different browsers, can give different results.

**Comment by ShadowBB** [comment]
While I agree with all of this I am unsure where(!) this should be clarified. Should we mention this in the glossary with "accessibility tree" or somewhere else?

**Comment by Jym77** [comment]
I agree that the Accessibility tree is far from being well defined (in real life), with each browser implementing some parts of it in a different way (and the specs saying yet something else). Having it as an input aspect would solve that issue. Some related thoughts:

1. This is more or less already what we do when we have as input aspect the *DOM tree*, rather than the *source code*. We do not consider the DOM tree to necessarily be the same everywhere but treat it as a black box. It makes sense to do the same with the accessibility tree.
2. However, many examples would then need to have the accessibility tree as part of the example. Especially given that it is different from one browser to another, it would make little sense to *not* give the accessibility tree as part of the example.
3. On the other hand, the DOM tree seems to be stable enough between browsers that we can infer it from the source code. This is why examples are usually written with the source code even when the input aspect is the DOM tree (thus, the example assumes that the DOM tree will be computed in the same way by all user agents).
4. Similarly, many examples of rules that take CSS styling as input aspect do not provide any CSS. It is likely assumed that there is no CSS for that particular example.
Also, if we add language as input aspect (as suggested in #671), we probably should add to all examples that the language is english.
5. At the very least we should add a big warning in the glossary definition of "included in the accessibility tree" that this depends on browser.

So, my main concern is that we will need to add accessibility tree to all examples while the current statu quo seems to be that we consider the spec as the "source code to accessibility tree" mapping.

**Comment by Jym77** [comment]
Another note: Accessibility tree is listed as one of the ACT-Rules "Common Input Aspects"
https://www.w3.org/TR/act-rules-aspects/#input-aspects-accessibility hinting that it was probably intended to be used…

However, this also says that 
> The means by which the accessibility tree is constructed, be it by a web browser or not, is not of importance as long as the construction follows any applicable specifications that might exist, such as the [Core Accessibility API Mappings 1.1 [CORE-AAM-1.1]](https://www.w3.org/TR/core-aam-1.1/).

So this seems to assume that the accessibility tree is uniquely determined from the DOM tree and the CSS styling and follows the specs (rather than being something that varies from browser to browser).

**Comment by Jym77** [comment]
I guess we're putting the AT in input aspects now and can probably close this.
@WilcoFiers ?
