### ISSUE TITLE
Mismatch in the applicability and expectation of rule de46e4

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#855]
In the rule [Valid body lang attribute](https://act-rules.github.io/rules/de46e4) (renamed to "Elements with lang attribute in body are valid" in #851) the applicability specifies elements that have lang **or** xml:lang attribute, while the expectation specifies elements that have lang **and** xml:lang attributes.

Expectation should be corrected so that they match.

**Comment by Jym77** [comment]
I agree that the discrepancy is also a bit annoying me… (and it's present in the other lang rules).

The applicability is for either `lang` or `xml:lang`, one is enough.
The expectation is for any of those that is actually here.

It would be wrong to change applicability to "any element that has a `lang` **and** `xml:lang`" since that would make `<div lang="xyz">` inapplicable instead of failed.
It would be wrong to change the expectation to "The `lang` **or** `xml:lang`" since that would make `<div lang="en" xml:lang="xyz">` pass instead of fail.

At the same time, the current formulation makes it a bit weird for `<div lang="en">` to pass. It does not have a valid subtag for `lang` **and** `xml:lang` since it does not have `xml:lang`…
I guess a better expectation would be "each of the `lang` and `xml:lang` attribute that exists and is not empty has a valid subtag".

**Comment by Jym77** [comment]
I think this is _de facto_ closed by #934.
