### ISSUE TITLE
Ligature fonts fail "Visible label is part of accessible name " (2ee8b8)

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#975]
Ligature fonts can be used as icons, things like this:

```html
<span aria-label="Remove" style="font-family: \'LigatureSymbols\'">delete</span>
```

In a case like this, "delete" should not be treated as visible text, as the entire word is replaced with an icon.

**Comment by Jym77** [comment]
1. I am not sure what you mean given that I see no difference in rendering between this element with or without the `style` attribute (Chrome, Edge, Firefox). Notably, I can select individual letters from the element with the `style` attribute and don't understand what you mean by " the entire word is replaced with an icon".
It might be due to a font not being installed on my computer, which at the very least show that this issue is tricky (it depends on what's on the user's computer).

2. Would adding an assumption to the rule about CSS/font not hijacking the content be enough? Similar assumptions are already added as part of [the update to this rule](https://github.com/act-rules/act-rules.github.io/pull/452/files#diff-1a5912f37157673b7f8815ddefe956aeR41-R42).

**Comment by jkodu** [comment]
@WilcoFiers wdyt about https://github.com/act-rules/act-rules.github.io/issues/975#issuecomment-542123852

**Comment by WilcoFiers** [comment]
I'm not going to put this in an assumption, because this scenario isn't theoretical. You can find an example of this in the icons in the nav on news.google.com.
